openapi: 3.0.3
info:
  title: Sternula Sandbox Control Interface 
  version: 1.0.1
  description: >-
    Interface to be used by Sternula VDES/MMS Sandbox users to set and query settings of their respective sandbox, authenticated by http basic authentication. 
    Copyright Sternula Aps, Denmark, 2019, 2020
    May be used to work with the <a href="https://www.sternula.com/index.php/product-vdes-testplatform/">Sternula Sandbox Product</a>.
  termsOfService: 'https://www.sternula.com/index.php/general-terms-and-conditions/'
  contact:
    name: Sternula
    url: 'https://www.sternula.com'
#===paths===
paths:
  /vdes_:
    post:
      tags:
        - config
      summary: VDE-SAT configuration
      description: Change the start_time or the number_of_satellites to be used in the VDE-SAT network model. Only one of the parameters must be set.
      requestBody:
        content:
          application/json:
            schema:
                oneOf:
                - $ref: '#/components/schemas/Constellation_time'
                - $ref: '#/components/schemas/Constellation_number_of_satellites'
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable Entity
  /start:
    post:
      tags: 
        - config
      summary: Start VDE-SAT network
      description: Start the VDE-SAT network acording to last uploaded configuration.
      responses:
        '200':
          description: Started
        '400':
          description: Unable to start
  /shutdown:
    post:
      tags: 
        - config
      summary: Shutdown the VDE-SAT network
      description: Shutdown the VDE-SAT network.
      responses:
        '200':
          description: Shutdown
        '400':
          description: Unable to shutdown
  #---Ships---
  /ships:
    get:
      tags:
        - ship
      summary: get a list of ships
      description: 'Get the list of ships in the simulation.'
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfShips'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - ship
      summary: Add a new ship
      description: 'Add a new ship to the VDE-SAT network model'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ship'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Mmsi'
          links:
            GetShipByMMSI:
              operationId: getShip
              parameters:
                MMSI: '$response.body#/MMSI'
              description: Link to the created ship.
        '422':
          description: Unprocessable Entity
  /ships/{MMSI}:
    parameters:
      - in: path
        name: MMSI
        required: true
        description: MMSI of the ship
        schema:
           $ref: '#/components/schemas/Mmsi'
    # delete
    delete:
      tags:
        - ship
      summary: Delete a ship from the simulation. It will not be possible to receive messages for that ship anymore. The VDE-SAT network will forget that this ship existed. Messages cannot be transferred to this ship anymore.
      responses:
        '204':
          description: Ship was deleted.    
        '404':
          description: not found
    # get
    get:
      tags:
        - ship
      summary: Get a ship by MMSI
      operationId: getShip
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
        '404':
          description: not found 
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
  #---coaststations---
  /coaststations:
    get:
      tags:
        - coaststation
      summary: get a list of coast stations
      description: Get the list of coast stations in the simulation.
      operationId: getAllCoastStation
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfCoastStations'
    # post
    post:
      tags:
        - coaststation
      summary: Add a new coast station
      description: 'Add a new coast station to the VDE-SAT network model'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoastStation'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Mmsi'
          links:
            GetCoastStationByMMSI:
              operationId: getCoastStation
              parameters:
                MMSI: '$response.body#/MMSI'
              description: Link to the created coast station.
        '422':
          description: Unprocessable Entity
  /coaststations/{MMSI}:
    parameters:
      - in: path
        name: MMSI
        schema:
           $ref: '#/components/schemas/Mmsi'
        required: true
        description: MMSI of the coast station
    # delete
    delete:
      tags:
        - coaststation
      summary: Delete a coast station from the simulation. The VDE-SAT network will forget that this coast station existed. Messages cannot be transferred through this coast station anymore.
      responses:
        '204':
          description: Coast station was deleted.    
        '404':
          description: Not Found - no coastal station with this MMSI was found.
    # get
    get:
      tags:
        - coaststation
      summary: Get a coast station by MMSI
      operationId: getCoastStation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoastStation'
        '404':
          description: Not Found - no coast station with this MMSI was found
#===== Components =====
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Error:
      description: To be returned on error. Includes error code and optionally a description of the error.
      type: object
      properties:
        errorCause:
          type: string
          enum: [unspecified, 
                 position_of_destination_unknown,
                 message_too_long,
                 authentication_failure,
                 unknown_destination,
                 too_late_to_cancel]
        errorMessage:
          type: string
      required:
        - errorCause
    Mmsi:
      description: Maritime Mobile Service Identity
      type: string
      minLength: 9
      maxLength: 9
      format: mmsi
      pattern: '^\d{9}$'
      example: '220243167'
    latitude:
      description: latitude in Decimal Degrees
      type: number
      format: degrees
      minimum: -90.0
      maximum: +90.0
      example: 56.9729       
    longitude:
      description: longitude in Decimal Degrees
      type: number
      format: degrees
      minimum: -180.0
      maximum: +180.0
      example: 10.33360 
    #---conf---
    Constellation_time:
      type: object
      properties:
        start_time: 
          description: Constellation calculated from Sternula's roadmap and the given time. Used in the following VDE-SAT network simulations until changed.
          type: string
          format: date-time
        interference_conditions:
          $ref: '#/components/schemas/Interference_conditions'
        time_factor:
          $ref: '#/components/schemas/Time_factor'
    Constellation_number_of_satellites:
      type: object
      properties:
        number_of_satellites:      
          description: Number of satellites used in the following VDE-SAT network simulations until changed. Shall not be specified if year is specified.
          type: integer
          minimum: 1
          maximum: 140
          example: 4
        interference_conditions:
          $ref: '#/components/schemas/Interference_conditions'
        time_factor:
          $ref: '#/components/schemas/Time_factor'
    Interference_conditions:
      description: gives the possibility to assume good or bad conditions for the transmissions.
      type: string
      enum: [bad, normal, good]
      default: normal
    Time_factor:
      description: the factor applied to the time clock in the simulation. If e.g. set to 10, a 60 minute interval in the simulated network will only take 6 minutes in realtime. Default is a factor of 1.
      type: integer
      minimum: 1
      maximum: 10000
      example: 10
    #---ship---  
    ListOfShips:
      type: array
      items:
        type: object
        properties:
          MMSI: 
            $ref: '#/components/schemas/Mmsi'
    Ship:
      type: object
      required:
        - MMSI
        - latitude
        - longitude
      properties:
        MMSI:
          $ref: '#/components/schemas/Mmsi'
        latitude:
          $ref: '#/components/schemas/latitude'
        longitude:
          $ref: '#/components/schemas/longitude'
    #---coast stations--- 
    ListOfCoastStations:
      type: array
      items:
        type: object
        properties:
          MMSI: 
            $ref: '#/components/schemas/Mmsi'
    CoastStation:
      type: object
      required:
        - MMSI
        - coverage
      properties:
        MMSI:
          $ref: '#/components/schemas/Mmsi'
        coverage:
          type: array
          uniqueItems: true
          items:
            type: object
            required:
              - lon
              - lat            
            properties:
              lon: 
                $ref: '#/components/schemas/longitude'
              lat: 
                $ref: '#/components/schemas/latitude'
          minItems: 3
          maxItems: 16
          example: 
            - lon: 10.222
              lat: 56.822
            - lon: 10.222
              lat: 57.142
            - lon: 10.4042
              lat: 57.142
            - lon: 10.4042
              lat: 56.822
  #---responses---
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
#--------
security:
  - BasicAuth: []
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/overgaard/sternula-sandbox_control_interface/1.0.1